import {
  FaBus,
  FaCar,
  FaPlaneDeparture,
  FaStore,
  FaCapsules,
  FaCamera,
  FaCashRegister,
  FaDumbbell,
  FaPaw,
  FaShip,
  FaRegGem,
  FaPiggyBank,
  FaPaintRoller,
  FaLandmark,
  FaKey,
  FaGift,
  FaBabyCarriage,
  FaShopify,
  FaBookOpen,
  FaCoins,
  FaCouch,
  FaFlagCheckered,
  FaGlasses,
  FaMusic,
  FaLightbulb,
  FaMedapps,
  FaLock,
  FaShower,
  FaSnowplow,
  FaTractor,
  FaUtensils,
  FaWrench,
  FaUserGraduate,
  FaTrain,
  FaDesktop,
} from "react-icons/fa";

const IconsList = [
  { id: 1, name: "bus", component: FaBus },
  { id: 2, name: "car", component: FaCar },
  { id: 3, name: "plane-departure", component: FaPlaneDeparture },
  { id: 4, name: "store", component: FaStore },
  { id: 5, name: "capsules", component: FaCapsules },
  { id: 6, name: "camera", component: FaCamera },
  { id: 7, name: "cash-register", component: FaCashRegister },
  { id: 8, name: "dumbbell", component: FaDumbbell },
  { id: 9, name: "paw", component: FaPaw },
  { id: 10, name: "ship", component: FaShip },
  { id: 11, name: "gem", component: FaRegGem },
  { id: 12, name: "piggy-bank", component: FaPiggyBank },
  { id: 13, name: "paint-roller", component: FaPaintRoller },
  { id: 14, name: "landmark", component: FaLandmark },
  { id: 15, name: "key", component: FaKey },
  { id: 16, name: "gift", component: FaGift },
  { id: 17, name: "baby-carriage", component: FaBabyCarriage },
  { id: 18, name: "shopify", component: FaShopify },
  { id: 19, name: "book-open", component: FaBookOpen },
  { id: 20, name: "coins", component: FaCoins },
  { id: 21, name: "couch", component: FaCouch },
  { id: 22, name: "flag-checkered", component: FaFlagCheckered },
  { id: 23, name: "glasses", component: FaGlasses },
  { id: 24, name: "music", component: FaMusic },
  { id: 25, name: "lightbulb", component: FaLightbulb },
  { id: 26, name: "medapps", component: FaMedapps },
  { id: 27, name: "lock", component: FaLock },
  { id: 28, name: "shower", component: FaShower },
  { id: 29, name: "snowplow", component: FaSnowplow },
  { id: 30, name: "tractor", component: FaTractor },
  { id: 31, name: "utensils", component: FaUtensils },
  { id: 32, name: "wrench", component: FaWrench },
  { id: 33, name: "user-graduate", component: FaUserGraduate },
  { id: 34, name: "train", component: FaTrain },
  { id: 35, name: "online-shop", component: FaDesktop  },

];

export default IconsList;
